// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3tvBD2liyqbvcsMbQlaNwL7wj6UdO4z8',
    appId: '1:555250860137:web:d69a58747771cc47b522f8',
    messagingSenderId: '555250860137',
    projectId: 'piyoplate',
    authDomain: 'piyoplate.firebaseapp.com',
    storageBucket: 'piyoplate.firebasestorage.app',
    measurementId: 'G-Y0LNG1SM8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5PjjBGFSNO3gWOjx5azBA-2LZnT18hZU',
    appId: '1:555250860137:android:76f3856dfec1249cb522f8',
    messagingSenderId: '555250860137',
    projectId: 'piyoplate',
    storageBucket: 'piyoplate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaweWUISW2EzdTjuGSpg8NlrB1SLld-8Q',
    appId: '1:555250860137:ios:9ded44c588d1258eb522f8',
    messagingSenderId: '555250860137',
    projectId: 'piyoplate',
    storageBucket: 'piyoplate.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaweWUISW2EzdTjuGSpg8NlrB1SLld-8Q',
    appId: '1:555250860137:ios:9ded44c588d1258eb522f8',
    messagingSenderId: '555250860137',
    projectId: 'piyoplate',
    storageBucket: 'piyoplate.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3tvBD2liyqbvcsMbQlaNwL7wj6UdO4z8',
    appId: '1:555250860137:web:d922751c43ec03b4b522f8',
    messagingSenderId: '555250860137',
    projectId: 'piyoplate',
    authDomain: 'piyoplate.firebaseapp.com',
    storageBucket: 'piyoplate.firebasestorage.app',
    measurementId: 'G-TFXZ1P5LBW',
  );
}
